CREATE TABLE exchange_rate (
    id BIGSERIAL PRIMARY KEY,
    currency_from VARCHAR(10) NOT NULL,
    currency_to VARCHAR(10) NOT NULL,
    ratio DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE exchange_history (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    currency_from VARCHAR(10) NOT NULL,
    amount_from DOUBLE PRECISION NOT NULL,
    currency_to VARCHAR(10) NOT NULL,
    amount_to DOUBLE PRECISION NOT NULL,
    ratio DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
